coverage:
  ignore:
    - "*/conftest.py"
    - "*/tests/conftest.py"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 2%
        base: auto
        paths:
          - "causalpy/"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
