#!/usr/bin/env python3
"""
Generate the how-to example gallery for the docs.

1. Render ``docs/source/notebooks/index.md`` from ``gallery.yaml``.
2. Extract thumbnail images from notebooks into ``_static/thumbnails/``.

Pass ``--check`` to verify sync without writing, ``--no-thumbnails`` to skip
the image extraction pass.
"""

from __future__ import annotations

import argparse
import base64
import io
import sys
from pathlib import Path
from typing import Any

import yaml

try:
    import nbformat
    from nbconvert.preprocessors import ExecutePreprocessor
except ImportError:
    nbformat = None  # type: ignore[assignment]
    ExecutePreprocessor = None  # type: ignore[assignment,misc]

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore[assignment,misc]

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOKS_DIR = REPO_ROOT / "docs" / "source" / "notebooks"
GALLERY_YAML = NOTEBOOKS_DIR / "gallery.yaml"
INDEX_MD = NOTEBOOKS_DIR / "index.md"
THUMBNAILS_DIR = REPO_ROOT / "docs" / "source" / "_static" / "thumbnails"

GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_gallery.py from gallery.yaml. "
    "Do not edit by hand. -->\n"
)


def _notebook_stem(notebook: str) -> str:
    return Path(notebook).stem


def _notebook_docname(notebook: str) -> str:
    """Return the Sphinx docname file (with extension) for a notebook stem."""
    stem = _notebook_stem(notebook)
    ipynb = NOTEBOOKS_DIR / f"{stem}.ipynb"
    markdown = NOTEBOOKS_DIR / f"{stem}.md"
    if ipynb.exists():
        return ipynb.name
    if markdown.exists():
        return markdown.name
    return f"{stem}.ipynb"


def _iter_categories(data: dict[str, Any]) -> list[dict[str, Any]]:
    categories: list[dict[str, Any]] = []
    for group in data.get("groups", []):
        categories.extend(group.get("categories", []))
    return categories


def _iter_cards(data: dict[str, Any]) -> list[dict[str, Any]]:
    cards: list[dict[str, Any]] = []
    for category in _iter_categories(data):
        cards.extend(category.get("cards", []))
    return cards


def _render_grid(cards: list[dict[str, Any]]) -> list[str]:
    if not cards:
        return []

    block = [
        "::::{grid} 1 2 3 3",
        ":gutter: 3",
        "",
    ]
    for index, card in enumerate(cards):
        stem = _notebook_stem(card["notebook"])
        block.append(":::{grid-item-card} " + card["title"])
        block.append(":class-card: sd-card-h-100")
        if card.get("thumbnail", True):
            block.append(f":img-top: ../_static/thumbnails/{stem}.png")
        block.extend(
            [
                f":link: {stem}",
                ":link-type: doc",
                ":::",
            ]
        )
        if index < len(cards) - 1:
            block.append("")
    block.extend(["::::", ""])
    return block


def _render_hidden_toctree(caption: str, cards: list[dict[str, Any]]) -> list[str]:
    if not cards:
        return []

    block = [
        "::{toctree}",
        ":hidden:",
        f":caption: {caption}",
        ":maxdepth: 1",
        "",
    ]
    for card in cards:
        block.append(_notebook_docname(card["notebook"]))
    block.extend([":::", ""])
    return block


def render_index_md(yaml_path: Path = GALLERY_YAML) -> str:
    data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))

    out = [
        "---",
        "html_theme.sidebar_secondary.remove: true",
        "---",
        "",
        GENERATED_BANNER.rstrip(),
        "",
        f"# {data['title']}",
        "",
        data["intro"].rstrip(),
        "",
    ]

    for group in data.get("groups", []):
        out.append(f"## {group['title']}")
        out.append("")
        if intro := group.get("intro"):
            out.append(intro.rstrip())
            out.append("")

        for category in group.get("categories", []):
            out.append(f"## {category['title']}")
            out.append("")
            if intro := category.get("intro"):
                out.append(intro.rstrip())
                out.append("")
            out.extend(_render_grid(category.get("cards", [])))

    out.extend(
        [
            "<!-- Hidden toctrees feed the left Section Navigation sidebar. -->",
            "",
        ]
    )
    for category in _iter_categories(data):
        caption = category.get("toctree_caption", category["title"])
        out.extend(_render_hidden_toctree(caption, category.get("cards", [])))

    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def check_coverage(data: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Return ``(missing, orphan)`` notebook stems vs gallery.yaml."""
    listed = {_notebook_stem(card["notebook"]) for card in _iter_cards(data)}

    on_disk: set[str] = set()
    for path in NOTEBOOKS_DIR.iterdir():
        if path.suffix in {".ipynb", ".md"} and path.name not in {
            "index.md",
            "gallery.yaml",
        }:
            on_disk.add(path.stem)

    missing = sorted(on_disk - listed)
    orphan = sorted(listed - on_disk)
    return missing, orphan


def generate_or_check_index_md(check: bool = False) -> int:
    data = yaml.safe_load(GALLERY_YAML.read_text(encoding="utf-8"))
    rendered = render_index_md()
    missing, orphan = check_coverage(data)

    status = 0
    if missing:
        print("gallery.yaml is missing entries for these notebooks:", file=sys.stderr)
        for notebook in missing:
            print(f"  - {notebook}", file=sys.stderr)
        status = 1
    if orphan:
        print("gallery.yaml lists notebooks that are not on disk:", file=sys.stderr)
        for notebook in orphan:
            print(f"  - {notebook}", file=sys.stderr)
        status = 1

    on_disk = INDEX_MD.read_text(encoding="utf-8") if INDEX_MD.exists() else ""
    if check:
        if rendered != on_disk:
            print(
                f"{INDEX_MD.relative_to(REPO_ROOT)} is out of sync with "
                f"{GALLERY_YAML.relative_to(REPO_ROOT)}. "
                "Run `python scripts/generate_gallery.py` to regenerate.",
                file=sys.stderr,
            )
            status = 1
        return status

    if rendered != on_disk:
        INDEX_MD.write_text(rendered, encoding="utf-8")
        print(f"Wrote {INDEX_MD.relative_to(REPO_ROOT)}")
    else:
        print(f"{INDEX_MD.relative_to(REPO_ROOT)} already up to date")
    return status


def _find_image_in_notebook(nb) -> str | None:
    for cell in nb.cells:
        if cell.cell_type == "code" and hasattr(cell, "outputs") and cell.outputs:
            for output in cell.outputs:
                if output.output_type in ("display_data", "execute_result") and (
                    image_data := output.get("data", {}).get("image/png")
                ):
                    return image_data
    return None


def _save_thumbnail(notebook_path: Path, output_dir: Path, image_data: str) -> None:
    thumbnail_path = output_dir / f"{notebook_path.stem}.png"
    img = Image.open(io.BytesIO(base64.b64decode(image_data))).convert("RGB")
    target_size = (400, 250)
    target_w, target_h = target_size
    scale = max(target_w / img.width, target_h / img.height)
    resized = img.resize(
        (int(img.width * scale), int(img.height * scale)),
        Image.Resampling.LANCZOS,
    )
    left = (resized.width - target_w) // 2
    top = (resized.height - target_h) // 2
    resized.crop((left, top, left + target_w, top + target_h)).save(thumbnail_path)


def extract_first_image(notebook_path: Path, output_dir: Path) -> None:
    if Image is None or nbformat is None or ExecutePreprocessor is None:
        return

    try:
        nb = nbformat.reads(notebook_path.read_text(encoding="utf-8"), as_version=4)
        if image_data := _find_image_in_notebook(nb):
            _save_thumbnail(notebook_path, output_dir, image_data)
            return

        if not any(
            cell.cell_type == "code" and hasattr(cell, "outputs") and cell.outputs
            for cell in nb.cells
        ):
            print(f"  Executing {notebook_path.name} to generate thumbnail...")
            try:
                ExecutePreprocessor(timeout=120, kernel_name="python3").preprocess(
                    nb, {"metadata": {"path": str(notebook_path.parent)}}
                )
                if image_data := _find_image_in_notebook(nb):
                    _save_thumbnail(notebook_path, output_dir, image_data)
            except Exception as exc:
                print(f"  Warning: Failed to execute {notebook_path.name}: {exc}")
    except Exception as exc:
        print(f"Warning: Could not generate thumbnail for {notebook_path.name}: {exc}")


def generate_thumbnails() -> None:
    THUMBNAILS_DIR.mkdir(parents=True, exist_ok=True)
    data = yaml.safe_load(GALLERY_YAML.read_text(encoding="utf-8"))

    stems = {
        _notebook_stem(card["notebook"])
        for card in _iter_cards(data)
        if card.get("thumbnail", True)
    }
    notebook_files = [
        NOTEBOOKS_DIR / f"{stem}.ipynb"
        for stem in sorted(stems)
        if (NOTEBOOKS_DIR / f"{stem}.ipynb").exists()
    ]

    if not notebook_files:
        print("No notebooks found for thumbnails!")
        return

    print(f"Found {len(notebook_files)} notebooks for thumbnails")
    for notebook_path in notebook_files:
        print(f"Processing {notebook_path.name}...")
        extract_first_image(notebook_path, THUMBNAILS_DIR)
    print(f"Thumbnails saved to {THUMBNAILS_DIR}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write index.md or thumbnails; exit non-zero if out of sync.",
    )
    parser.add_argument(
        "--no-thumbnails",
        action="store_true",
        help="Skip thumbnail extraction.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    status = generate_or_check_index_md(check=args.check)
    if status:
        return status

    if args.check or args.no_thumbnails:
        return 0

    generate_thumbnails()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
