name: "PR Issue Label Sync"

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited]

permissions: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: read  # to read labels from linked issues

    steps:
      - name: Sync labels from closing issues
        uses: williambdean/closing-labels@f4c2fcadcb3df832d1cb6db483d79df85647acec # v0.0.7
        with:
          exclude: "help wanted,good first issue"
          respect_unlabeled: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
