name: Test Notebooks

on:
  pull_request:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "causalpy/**"
      - ".github/workflows/test_notebook.yml"
      - "scripts/run_notebooks/**"
      - "docs/source/notebooks/**"
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "causalpy/**"
      - ".github/workflows/test_notebook.yml"
      - "scripts/run_notebooks/**"
      - "docs/source/notebooks/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  notebooks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 60
    strategy:
      matrix:
        split:
          - "--pattern *-pymc.ipynb"
          - "--pattern *-sklearn.ipynb"
          - "--exclude-pattern=pymc --exclude-pattern=sklearn"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test,docs]"

      - name: Run notebooks
        run: python scripts/run_notebooks/runner.py ${{ matrix.split }}
